### ISSUE TITLE
Q: How to generate the model?

### ISSUE THREAD

**Issue by nuaimat** [AlexBabescu/freqgym#1]
Just a general question, I don't have much experience w/ machine learning, and might be missing the obvious, but i notice that the strategy is expecting this model: 
PPO.load('models/best_model_SimpleROIEnv_PPO_20211028_104631')

but it's not in the repo (model folder is empty) 
any leads on how to generate it please? 

Thanks

**Comment by AlexBabescu** [comment]
You will have to use train_freqtrade.py to train a model.

**Comment by nuaimat** [comment]
Thank you! this is amazing work, good job, closing this issue.
